### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by XLR-ZX** [MattRob1nson/REDBetter#3]
After successfully uploading around ~250 torrents, the script suddenly hit a roadblock.

```Traceback (most recent call last):
  File "./redactedbetter", line 276, in <module>
    main()
  File "./redactedbetter", line 157, in main
    artist = group['group']['musicInfo']['artists'][0]['name']
IndexError: list index out of range```

No further uploading can be done.

**Comment by MattRob1nson** [comment]
Could you please send me a PM on RED with the link to the torrent that you were transcoding when you experienced this issue?

**Comment by XLR-ZX** [comment]
For some reason it now continues past the

[This is the last successful torrent.](https://redacted.ch/torrents.php?id=23199&torrentid=16030) This is [the one it fails on.](https://redacted.ch/torrents.php?id=370211&torrentid=757029)

Oddly enough, these aren't the torrents I originally posted about. REDBetter now moves past the [original problem torrent](https://redacted.ch/torrents.php?id=816833&torrentid=1881587) and chokes on those instead. If it's somehow helpful, it originally choked on page 8 and now chokes on page 10.

**Comment by MattRob1nson** [comment]
So the torrent that it has a problem with changes? What do you mean when you say page 8/10?

**Comment by XLR-ZX** [comment]
>So the torrent that it has a problem with changes?

Yes.

>What do you mean when you say page 8/10?

My profile's snatch list, which your script works through.

**Comment by BoBeR182** [comment]
```
Logging in to RED...
Searching for transcode candidates...
+----------------------------------------------------------------------------------------------+
Release artist(s): Various Artists
Release name     : Crusade
Release year     : 2020
Release URL      : https://redacted.ch/torrents.php?id=1261876&torrentid=2703886#torrent2703886
+----------------------------------------------------------------------------------------------+
Formats needed: V0, 320
A FLAC file in this release has unacceptable tags - skipping: "/Marshmello x SVDDEN DEATH - Crusade/Marshmello x SVDDEN DEATH - Crusade.flac" has no tracknumber tag
You might be able to trump it.
Traceback (most recent call last):
  File "./redactedbetter", line 276, in <module>
    main()
  File "./redactedbetter", line 157, in main
    artist = group['group']['musicInfo']['artists'][0]['name']
IndexError: list index out of range
```

**Comment by BoBeR182** [comment]
This seems to be the torrent with issues.
https://redacted.ch/torrents.php?id=913367&torrentid=1967981#torrent1967981

**Comment by BoBeR182** [comment]
Upon more investigation, it looks like classical music albums that don't have an Artist ID, and just Composer IDs, cause this to crash the script.

**Comment by undaunt** [comment]
@BoBeR182 How are you detecting the next item in the list which is causing the crash? When I load mine up, I see two repeated and it crashes at/after the second torrent group, but that one does have an artist listed. And those two are not next to each other chronologically in my snatch list so I don't know where to look for the upcoming. Is it in the logs somehow?

**Comment by undaunt** [comment]
@BoBeR182 I put in a crappy hack to the code to test and it turns out mine was getting stuck on a torrent that has an artist as a DJ / Compiler - torrentid=2764892#torrent2764892. So yes, seems that your hunch is correct.

My hack is as follows, after 

```
artist = "";
            if len(group['group']['musicInfo']['artists']) > 1:
                artist = "Various Artists"
```

and before

```
            else:
                artist = group['group']['musicInfo']['artists'][0]['name']
```

add 

```
            elif len(group['group']['musicInfo']['artists']) == 0:
                artist = "Various - See Composer"
```

However this doesn't work legit - ideally we could get actual handling for this in where it would query the DJ / Compiler and/or Composer instead and substitute in that value instead of simply setting to various, which is wrong.

**Comment by mildvenus** [comment]
This should be fixed if we add these after:

            artist = "";
            if len(group['group']['musicInfo']['artists']) > 1:
                artist = "Various Artists"
            elif not group['group']['musicInfo']['artists'] and len(group['group']['musicInfo']['composers']) > 1:
                artist = "Various Artists"
            elif not group['group']['musicInfo']['artists'] and len(group['group']['musicInfo']['composers']):
                artist = group['group']['musicInfo']['composers'][0]['name']
            else:
                artist = group['group']['musicInfo']['artists'][0]['name']

**Comment by undaunt** [comment]
@mildvenus I wrote up something similar in a branch I'm working on, but with DJs and Composers. Not a python guy so wasn't sure how to do the negation and and/or, so I can probably clean mine up further tomorrow.
