### ISSUE TITLE
Individual torrent won't upload

### ISSUE THREAD

**Issue by XLR-ZX** [MattRob1nson/REDBetter#4]
```
./redactedbetter https://redacted.ch/torrents.php?torrentid=2416418
/home/x/.local/lib/python2.7/site-packages/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 2, 3]) may cause slowdown.
  warnings.warn(warning, RequestsDependencyWarning)
Logging in to RED...
Searching for transcode candidates...
You supplied one or more release URLs, ignoring your configuration's media types.
Traceback (most recent call last):
  File "./redactedbetter", line 276, in <module>
    main()
  File "./redactedbetter", line 144, in main
    [dict(urlparse.parse_qsl(urlparse.urlparse(url).query)) for url in args.release_urls]]
KeyError: 'id'
```

**Comment by MattRob1nson** [comment]
You appear to be linking the group, rather than an individual torrent.

Rather than https://redacted.ch/torrents.php?torrentid=2416418 the link should be https://redacted.ch/torrents.php?id=1126344\&torrentid=2416418

You may find this extension useful: https://redacted.ch/forums.php?action=viewthread&threadid=668
