### ISSUE TITLE
ImportError: No module named mutagen

### ISSUE THREAD

**Issue by awsms** [MattRob1nson/REDBetter#8]
Traceback (most recent call last):
  File "/home/***/bin/red", line 12, in <module>
    import tagging
  File "/home/***/REDBetter/tagging.py", line 30, in <module>
    import mutagen
ImportError: No module named mutagen

Mutagen is installed, so I don't know what the hell is going on :x

**Comment by scatking** [comment]
maybe default version is python3, and Mutagen is installed for python3.
you should try  pip2 install Mutagen
It maybe work.
